trigger:
- main

resources:
 pipelines:
  - pipeline: buildContosoAir # identifier for the resource used in pipeline resource variables
    source: Student1-36553574.ContosoAir # name of the pipeline that produces the artifact

pool:
  vmImage: ubuntu-latest